### ISSUE TITLE
Error using Material UI Components

### ISSUE THREAD

**Issue by AleffHenrique** [emmenko/redux-react-router-async-example#57]
I was changing components to use Material UI awesome ones when I tried implement a Selectable List (see: http://www.material-ui.com/#/components/list) and I got this very funny error:

```
0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.3.12
3 info using node@v5.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle redux-react-router-async-example@0.0.1~prestart: redux-react-router-async-example@0.0.1
6 silly lifecycle redux-react-router-async-example@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle redux-react-router-async-example@0.0.1~start: redux-react-router-async-example@0.0.1
8 verbose lifecycle redux-react-router-async-example@0.0.1~start: unsafe-perm in lifecycle true
9 c:\Users\Aleff\Desktop\github\redux-react-router-async-example
11 silly lifecycle redux-react-router-async-example@0.0.1~start: Args: [ '/d /s /c', 'npm run build && node server.js' ]
12 silly lifecycle redux-react-router-async-example@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle redux-react-router-async-example@0.0.1~start: Failed to exec start script
14 verbose stack Error: redux-react-router-async-example@0.0.1 start: `npm run build && node server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (c:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (c:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid redux-react-router-async-example@0.0.1
16 verbose cwd c:\Users\Aleff\Desktop\github\redux-react-router-async-example
17 error Windows_NT 10.0.10586
18 error argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v5.3.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error redux-react-router-async-example@0.0.1 start: `npm run build && node server.js`
22 error Exit status 1
23 error Failed at the redux-react-router-async-example@0.0.1 start script 'npm run build && node server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the redux-react-router-async-example package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build && node server.js
23 error You can get their info via:
23 error     npm owner ls redux-react-router-async-example
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Any idea about what did happen?

**Comment by emmenko** [comment]
Hmm, not sure. I see you are using windows and node 5 + npm 3. Haven't tested with those yet.
If you can, could you try it with node 0.12 + npm 2.14 ? Just to be sure it works on windows. I'll try with a different version of node.
